### ISSUE TITLE
Fix candidate code handling

### ISSUE THREAD

**Issue by lancew** [lancew/Scientist#16]
We accidentally removed the eval around the candidate code.
( https://github.com/lancew/Scientist/commit/20b7133677e2b4717fcd0222c3b0edac191d062a )

Two things:
1. Why did tests not catch this.
2. Put it back in.

Bonus:
3. Should control code also be eval'd?

**Comment by jkeroes** [comment]
4. Shouldn't we use Try::Tiny instead of eval { ... }?

**Comment by JRaspass** [comment]
@jkeroes I'm not sure we should, we're not writing an application here, we're writing a library to be consumed by other applications. As such we shouldn't force too many non-core deps onto our users.

Additionally we may want to rethink our use of Moo and Types::Standard, Scientist should be a couple of hundred lines tops, bless and hand written accessors should suffice and should prevent anyone dismissing our module on the grounds of it's long tail.

Furthermore Try::Tiny only offers a tiny bit of syntactical sugar over eval {} if ($@) {}, especially if we don't need to store the error? Perhaps we should warn it? Need to check what upstream ruby does.

**Comment by jkeroes** [comment]
If we're not capturing the error (and don't intend to) then eval {} is fine.

**Comment by jkeroes** [comment]
On the use of non-core modules, we certainly could do it that way. That said, anyone who's considering the use of this module probably understands what CPAN is, how it works, and how to install modules from it. A few no-core deps—especially Moo and Types::Standard—won't get in their way much.

Does it have its place? Sure! We have two options there: on one hand, we could drop it into Tiny::Scientist and on the other hand, finish these pull releases, and then backport this module to perl-5.8.

**Comment by lancew** [comment]
Not sure how we break these into individual pull requests so I can tackle one at a time?
I'd like to get the eval back in asap; but want to read through others so I can keep up to speed on what you are proposing. :-)

**Comment by jkeroes** [comment]
I'll cut a new branch and put the eval patch in alone. be ready in a few...

**Comment by jkeroes** [comment]
The bonus question warrants a new thread. Created #24 for that discussion.
