### ISSUE TITLE
Incorrect version in Changes

### ISSUE THREAD

**Issue by manwar** [lancew/Scientist#32]
Hi @lancew 

Just noticed the incorrect version, instead of 0.011, it still says 0.010, in the Changes file.
I would have created PR, if it had latest code ;-)

0.010 2018-02-10
    - Messed up the date of the release, so this simply fixes that
0.010 2018-02-10
    - Reduce how much of Test2 we import (JRaspass)
    - Removed 5.8 from travis a Devel::Cover does not work (Jraspass), Scientist itself works OK
    - Increase testing via travis to 5.24 and 5.26 (Jraspass)
    - Test2::Bundle::Extended is deprecated and replaced with Test2::V0 (Manwar)
    - Documentation tidy-up (Manwar)
    - Generate MetaJSON automaticall (Manwar)

Best Regards,
Mohammad S Anwar

**Comment by lancew** [comment]
I broke the first rule of releasing... don't do it late at night

**Comment by lancew** [comment]
https://metacpan.org/changes/release/LANCEW/Scientist-0.012
