### ISSUE TITLE
t/result.t started to fail (with newest Test2::Suite?)

### ISSUE THREAD

**Issue by eserte** [lancew/Scientist#35]
The test suite started to fail:
```
    # Failed test 'Observation diagnostic correct'
    # at t/result.t line 76.
    # +-------------------------------+----+-------------------------------+
    # | CONTROL                       | OP | CANDIDATE                     |
    # +-------------------------------+----+-------------------------------+
    # | Test2::EventFacet::Info::Tabl | eq | +------+---------+----+------ |
    # | e=HASH(0x449c10c0)            |    | -----+\n                      |
    # |                               |    | | PATH | CONTROL | OP | CANDI |
    # |                               |    | DATE |\n                      |
    # |                               |    | +------+---------+----+------ |
    # |                               |    | -----+\n                      |
    # |                               |    | | [0]  | 20      | eq | 10    |
    # |                               |    |      |\n                      |
    # |                               |    | +------+---------+----+------ |
    # |                               |    | -----+                        |
    # +-------------------------------+----+-------------------------------+

# Failed test 'result_observation'
# at t/result.t line 83.
# Seeded srand with seed '20190514' from local date.
t/result.t ........... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests 
```

Statistical analysis suggests that the failure started with Test2::Suite 0.000121 (@exodist: FYI):
```
****************************************************************
Regression 'mod:Test2::V0'
****************************************************************
Name           	       Theta	      StdErr	 T-stat
[0='const']    	      1.0000	      0.0000	10713041544952426.00
[1='eq_0.000097']	      0.0000	      0.0000	   2.36
[2='eq_0.000100']	      0.0000	      0.0000	   1.06
[3='eq_0.000111']	      0.0000	      0.0000	   2.17
[4='eq_0.000114']	      0.0000	      0.0000	   1.12
[5='eq_0.000115']	      0.0000	      0.0000	   1.68
[6='eq_0.000116']	      0.0000	      0.0000	   0.00
[7='eq_0.000119']	      0.0000	      0.0000	   3.09
[8='eq_0.000121']	     -1.0000	      0.0000	-10607491763541680.00

R^2= 1.000, N= 144, K= 9
****************************************************************
```

**Comment by lancew** [comment]
Hi... thanks for the report. Taking a look into it now

**Comment by lancew** [comment]
Have uploaded a trial version to pause to see how it fares

**Comment by exodist** [comment]
I introduced a new 'Fail' event that combines the failed assertion and the diagnostics into a single event, some Test2::Suite tools were switched to use it.

I am thinking about how to avoid these kinds of issues in the future, I am thinking a test-testing tool that does not pay attention to the event types, but rather just pays attention to their effect. But you should not wait for that before updating your tests.

Sorry for the inconvenience.

**Comment by exodist** [comment]
oops, sorry, my last comment was not actually related to your failure. The issue is that raw-table data is now part of some events so that different tools and renderers can produce pretty tables from the raw data if desired.

**Comment by lancew** [comment]
Hi @exodist thanks for the context. Much appreciated.
I have a "fix" that gets the stringified table out, it's a bit "icky" as I need to force people onto v0.0.121 of Test2::*

The issue is this line:

`my $diag  = join "\n", $delta ? $delta->table : ();`

kludge/bodge/fix might be (when combined with forcing v0.0.121): 

`my $diag  = $delta ? $delta->table->as_string : '';`

**Comment by lancew** [comment]
@eserte @exodist I have a new DEV version of Scientist on CPAN now which seems to be working on cpantesters ok.
https://metacpan.org/pod/release/LANCEW/Scientist-0.013-TRIAL/lib/Scientist.pod

**Comment by eserte** [comment]
Yes, the development release looks good: http://matrix.cpantesters.org/?dist=Scientist+0.013-TRIAL
There are some red spots which are probably unrelated to this issue.

**Comment by lancew** [comment]
@eserte 0.13 proper now released. Thanks!!
